[package]
name = "jsoncodegen-extra"
version = "0.1.0"
edition = "2024"

[dependencies]
convert_case = "0.10"

jsoncodegen-iota = { path = "../iota" }

[dev-dependencies]
pretty_assertions = { version = "1" }
