[package]
name = "jsoncodegen-extra"
edition = "2024"
publish = false

[dependencies]
convert_case = "0.10"

jsoncodegen-iota = { path = "../iota" }

[dev-dependencies]
pretty_assertions = { version = "1" }
