[package]
name = "jsoncodegen-java"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
convert_case = "0.10"
serde_json = "1"
unicode-general-category = "1"

jsoncodegen = { path = "../core" }

[dev-dependencies]
pretty_assertions = { version = "1" }
