[package]
name = "jsoncodegen-java"
version = "0.1.0"
edition = "2024"

[dependencies]
convert_case = "0.10"
serde_json = "1"
unicode-general-category = "1"

jsoncodegen = { path = "../core" }
jsoncodegen-extra = { path = "../extra" }
jsoncodegen-iota = { path = "../iota" }
