[package]
name = "jcg"
version = "0.3.1"
edition = "2024"
authors = ["zahash <zahash.z@gmail.com>"]
description = "json code generation cli"
license = "MIT"
repository = "https://github.com/zahash/jsoncodegen/"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde_json = "1"
wasi = "0.14"
wit-bindgen = "0.48"

jsoncodegen-dispatch = { path = "../dispatch" }
