[package]
name = "jsoncodegen-test-utils"
version.workspace = true
edition.workspace = true

[dependencies]
serde_json = "1"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }
