[package]
name = "jsoncodegen"
version = "0.3.1"
edition = "2021"
authors = ["zahash <zahash.z@gmail.com>"]
description = "json code generation library"
license = "MIT"
repository = "https://github.com/zahash/jsoncodegen/"

[dependencies]
convert_case = "0.9"
serde_json = "1"

[dev-dependencies]
pretty_assertions = { version = "1" }

[features]
extra = []
