[package]
name = "jsoncodegen-rust"
version.workspace = true
edition.workspace = true

[dependencies]
convert_case = "0.10"
serde_json = "1"
syn = { version = "2", features = ["parsing"] }

jsoncodegen = { path = "../core" }
