[package]
name = "jsoncodegen-dispatch"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1"

jsoncodegen-java = { path = "../codegen-java" }
jsoncodegen-rust = { path = "../codegen-rust" }
