[package]
name = "jsoncodegen-dispatch"
version.workspace = true
edition.workspace = true

[dependencies]
serde_json = "1"

jsoncodegen-java = { path = "../codegen-java" }
jsoncodegen-rust = { path = "../codegen-rust" }
