[package]
name = "jsoncodegen-web"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1"
wasm-bindgen = "0.2"

jsoncodegen-dispatch = { path = "../dispatch" }
